apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-hello
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: python-flask-hello
  template:
    metadata:
      labels:
        app: python-flask-hello
    spec:
      containers:
      - image: docker.io/dreamcastnan/python-hello:latest
        name: python-flask-hello
        ports:
        - containerPort: 5000
